run:
  concurrency: 4
  timeout: 1m
  tests: false
  issues-exit-code: 1
output:
  format: colored-line-number

issues:
  max-issues-per-linter: 100
  max-same-issues: 100
  exclude-use-default: false
  exclude-rules:
    - linters:
        - revive
      text: "package-comments:"
  exclude:
    - "ST1000: at least one file in a package should have a package comment"

linters-settings:
  funlen:
    lines: 80

  staticcheck:
    go: "1.20"
    checks: ["all"]

  dupl:
    threshold: 50

  dogsled:
    max-blank-identifiers: 2

  errcheck:
    check-type-assertions: false
    check-blank: true

  govet:
    check-shadowing: true
    shadow:
      strict: true
    enable-all: true

linters:
  disable-all: true
  enable:
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - godot
    - ineffassign
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  presets:
    - comment
    - error
    - unused
