run:
  concurrency: 4
  timeout: 1m
  tests: false
  issues-exit-code: 0
output:
  format: colored-line-number

issues:
  exclude-use-default: false

linters-settings:
  dupl:
    threshold: 50

  dogsled:
    max-blank-identifiers: 2

  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable:
      - asmdecl
      - assign
      - atomic
      - atomicalign
      - bools
      - buildtag
      - cgocall 
      - composites
      - copylocks
      - deepequalerrors
      - errorsas
      - fieldalignment

linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - godot
    - ineffassign
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - exportloopref
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  presets:
    - comment 
    - error 
    - unused