name: "Test"

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.48.0
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Coverage     
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CI_CODECOV }}  
        file: ./coverage.out
        fail_ci_if_error: true